# CMake generated Testfile for 
# Source directory: C:/Projects/Quick
# Build directory: C:/Projects/Quick
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ParserTest "C:/Projects/Quick/Debug/test_parser.exe")
  set_tests_properties(ParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;77;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ParserTest "C:/Projects/Quick/Release/test_parser.exe")
  set_tests_properties(ParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;77;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ParserTest "C:/Projects/Quick/MinSizeRel/test_parser.exe")
  set_tests_properties(ParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;77;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ParserTest "C:/Projects/Quick/RelWithDebInfo/test_parser.exe")
  set_tests_properties(ParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;77;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ParserTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TypeParserTest "C:/Projects/Quick/Debug/test_type_parser.exe")
  set_tests_properties(TypeParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;83;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TypeParserTest "C:/Projects/Quick/Release/test_type_parser.exe")
  set_tests_properties(TypeParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;83;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TypeParserTest "C:/Projects/Quick/MinSizeRel/test_type_parser.exe")
  set_tests_properties(TypeParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;83;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TypeParserTest "C:/Projects/Quick/RelWithDebInfo/test_type_parser.exe")
  set_tests_properties(TypeParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;83;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(TypeParserTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AddTest "C:/Projects/Quick/Debug/test_add.exe")
  set_tests_properties(AddTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;88;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AddTest "C:/Projects/Quick/Release/test_add.exe")
  set_tests_properties(AddTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;88;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AddTest "C:/Projects/Quick/MinSizeRel/test_add.exe")
  set_tests_properties(AddTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;88;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AddTest "C:/Projects/Quick/RelWithDebInfo/test_add.exe")
  set_tests_properties(AddTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;88;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(AddTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CFGTest "C:/Projects/Quick/Debug/test_cfg.exe")
  set_tests_properties(CFGTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;94;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CFGTest "C:/Projects/Quick/Release/test_cfg.exe")
  set_tests_properties(CFGTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;94;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CFGTest "C:/Projects/Quick/MinSizeRel/test_cfg.exe")
  set_tests_properties(CFGTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;94;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CFGTest "C:/Projects/Quick/RelWithDebInfo/test_cfg.exe")
  set_tests_properties(CFGTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;94;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(CFGTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DomTreeTest "C:/Projects/Quick/Debug/test_dom.exe")
  set_tests_properties(DomTreeTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;100;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DomTreeTest "C:/Projects/Quick/Release/test_dom.exe")
  set_tests_properties(DomTreeTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;100;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DomTreeTest "C:/Projects/Quick/MinSizeRel/test_dom.exe")
  set_tests_properties(DomTreeTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;100;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DomTreeTest "C:/Projects/Quick/RelWithDebInfo/test_dom.exe")
  set_tests_properties(DomTreeTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;100;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(DomTreeTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DFTest "C:/Projects/Quick/Debug/test_df.exe")
  set_tests_properties(DFTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;106;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DFTest "C:/Projects/Quick/Release/test_df.exe")
  set_tests_properties(DFTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;106;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DFTest "C:/Projects/Quick/MinSizeRel/test_df.exe")
  set_tests_properties(DFTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;106;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DFTest "C:/Projects/Quick/RelWithDebInfo/test_df.exe")
  set_tests_properties(DFTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;106;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(DFTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PhiTest "C:/Projects/Quick/Debug/test_phi.exe")
  set_tests_properties(PhiTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;112;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PhiTest "C:/Projects/Quick/Release/test_phi.exe")
  set_tests_properties(PhiTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;112;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PhiTest "C:/Projects/Quick/MinSizeRel/test_phi.exe")
  set_tests_properties(PhiTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;112;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PhiTest "C:/Projects/Quick/RelWithDebInfo/test_phi.exe")
  set_tests_properties(PhiTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;112;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(PhiTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DIETest "C:/Projects/Quick/Debug/test_die.exe")
  set_tests_properties(DIETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;118;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DIETest "C:/Projects/Quick/Release/test_die.exe")
  set_tests_properties(DIETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;118;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DIETest "C:/Projects/Quick/MinSizeRel/test_die.exe")
  set_tests_properties(DIETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;118;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DIETest "C:/Projects/Quick/RelWithDebInfo/test_die.exe")
  set_tests_properties(DIETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;118;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(DIETest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DIEChainTest "C:/Projects/Quick/Debug/test_die_chain.exe")
  set_tests_properties(DIEChainTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;124;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DIEChainTest "C:/Projects/Quick/Release/test_die_chain.exe")
  set_tests_properties(DIEChainTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;124;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DIEChainTest "C:/Projects/Quick/MinSizeRel/test_die_chain.exe")
  set_tests_properties(DIEChainTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;124;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DIEChainTest "C:/Projects/Quick/RelWithDebInfo/test_die_chain.exe")
  set_tests_properties(DIEChainTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;124;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(DIEChainTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WindowsTest "C:/Projects/Quick/Debug/test_windows.exe")
  set_tests_properties(WindowsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;130;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WindowsTest "C:/Projects/Quick/Release/test_windows.exe")
  set_tests_properties(WindowsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;130;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WindowsTest "C:/Projects/Quick/MinSizeRel/test_windows.exe")
  set_tests_properties(WindowsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;130;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WindowsTest "C:/Projects/Quick/RelWithDebInfo/test_windows.exe")
  set_tests_properties(WindowsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;130;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(WindowsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RenameTest "C:/Projects/Quick/Debug/test_rename.exe")
  set_tests_properties(RenameTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;136;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RenameTest "C:/Projects/Quick/Release/test_rename.exe")
  set_tests_properties(RenameTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;136;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RenameTest "C:/Projects/Quick/MinSizeRel/test_rename.exe")
  set_tests_properties(RenameTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;136;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RenameTest "C:/Projects/Quick/RelWithDebInfo/test_rename.exe")
  set_tests_properties(RenameTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;136;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(RenameTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RenameLoadTest "C:/Projects/Quick/Debug/test_rename_load.exe")
  set_tests_properties(RenameLoadTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;142;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RenameLoadTest "C:/Projects/Quick/Release/test_rename_load.exe")
  set_tests_properties(RenameLoadTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;142;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RenameLoadTest "C:/Projects/Quick/MinSizeRel/test_rename_load.exe")
  set_tests_properties(RenameLoadTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;142;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RenameLoadTest "C:/Projects/Quick/RelWithDebInfo/test_rename_load.exe")
  set_tests_properties(RenameLoadTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;142;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(RenameLoadTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Mem2RegTest "C:/Projects/Quick/Debug/test_mem2reg.exe")
  set_tests_properties(Mem2RegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;148;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Mem2RegTest "C:/Projects/Quick/Release/test_mem2reg.exe")
  set_tests_properties(Mem2RegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;148;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Mem2RegTest "C:/Projects/Quick/MinSizeRel/test_mem2reg.exe")
  set_tests_properties(Mem2RegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;148;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Mem2RegTest "C:/Projects/Quick/RelWithDebInfo/test_mem2reg.exe")
  set_tests_properties(Mem2RegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;148;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(Mem2RegTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CopyElimTest "C:/Projects/Quick/Debug/test_copy_elim.exe")
  set_tests_properties(CopyElimTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;154;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CopyElimTest "C:/Projects/Quick/Release/test_copy_elim.exe")
  set_tests_properties(CopyElimTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;154;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CopyElimTest "C:/Projects/Quick/MinSizeRel/test_copy_elim.exe")
  set_tests_properties(CopyElimTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;154;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CopyElimTest "C:/Projects/Quick/RelWithDebInfo/test_copy_elim.exe")
  set_tests_properties(CopyElimTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;154;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(CopyElimTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GVNTest "C:/Projects/Quick/Debug/test_gvn.exe")
  set_tests_properties(GVNTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;160;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GVNTest "C:/Projects/Quick/Release/test_gvn.exe")
  set_tests_properties(GVNTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;160;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GVNTest "C:/Projects/Quick/MinSizeRel/test_gvn.exe")
  set_tests_properties(GVNTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;160;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GVNTest "C:/Projects/Quick/RelWithDebInfo/test_gvn.exe")
  set_tests_properties(GVNTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;160;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(GVNTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RegAllocTest "C:/Projects/Quick/Debug/test_regalloc.exe")
  set_tests_properties(RegAllocTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;166;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RegAllocTest "C:/Projects/Quick/Release/test_regalloc.exe")
  set_tests_properties(RegAllocTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;166;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RegAllocTest "C:/Projects/Quick/MinSizeRel/test_regalloc.exe")
  set_tests_properties(RegAllocTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;166;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RegAllocTest "C:/Projects/Quick/RelWithDebInfo/test_regalloc.exe")
  set_tests_properties(RegAllocTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;166;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(RegAllocTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RegAllocSpillTest "C:/Projects/Quick/Debug/test_regalloc_spill.exe")
  set_tests_properties(RegAllocSpillTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;172;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RegAllocSpillTest "C:/Projects/Quick/Release/test_regalloc_spill.exe")
  set_tests_properties(RegAllocSpillTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;172;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RegAllocSpillTest "C:/Projects/Quick/MinSizeRel/test_regalloc_spill.exe")
  set_tests_properties(RegAllocSpillTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;172;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RegAllocSpillTest "C:/Projects/Quick/RelWithDebInfo/test_regalloc_spill.exe")
  set_tests_properties(RegAllocSpillTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;172;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(RegAllocSpillTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LivenessTest "C:/Projects/Quick/Debug/test_liveness.exe")
  set_tests_properties(LivenessTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;178;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LivenessTest "C:/Projects/Quick/Release/test_liveness.exe")
  set_tests_properties(LivenessTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;178;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LivenessTest "C:/Projects/Quick/MinSizeRel/test_liveness.exe")
  set_tests_properties(LivenessTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;178;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LivenessTest "C:/Projects/Quick/RelWithDebInfo/test_liveness.exe")
  set_tests_properties(LivenessTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;178;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(LivenessTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SCCPTest "C:/Projects/Quick/Debug/test_sccp.exe")
  set_tests_properties(SCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;184;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SCCPTest "C:/Projects/Quick/Release/test_sccp.exe")
  set_tests_properties(SCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;184;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SCCPTest "C:/Projects/Quick/MinSizeRel/test_sccp.exe")
  set_tests_properties(SCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;184;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SCCPTest "C:/Projects/Quick/RelWithDebInfo/test_sccp.exe")
  set_tests_properties(SCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;184;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(SCCPTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WindowsStackTest "C:/Projects/Quick/Debug/test_windows_stack.exe")
  set_tests_properties(WindowsStackTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;190;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WindowsStackTest "C:/Projects/Quick/Release/test_windows_stack.exe")
  set_tests_properties(WindowsStackTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;190;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WindowsStackTest "C:/Projects/Quick/MinSizeRel/test_windows_stack.exe")
  set_tests_properties(WindowsStackTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;190;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WindowsStackTest "C:/Projects/Quick/RelWithDebInfo/test_windows_stack.exe")
  set_tests_properties(WindowsStackTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;190;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(WindowsStackTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CopyTest "C:/Projects/Quick/Debug/test_copy.exe")
  set_tests_properties(CopyTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;195;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CopyTest "C:/Projects/Quick/Release/test_copy.exe")
  set_tests_properties(CopyTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;195;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CopyTest "C:/Projects/Quick/MinSizeRel/test_copy.exe")
  set_tests_properties(CopyTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;195;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CopyTest "C:/Projects/Quick/RelWithDebInfo/test_copy.exe")
  set_tests_properties(CopyTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;195;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(CopyTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MulDivTest "C:/Projects/Quick/Debug/test_mul_div.exe")
  set_tests_properties(MulDivTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;200;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MulDivTest "C:/Projects/Quick/Release/test_mul_div.exe")
  set_tests_properties(MulDivTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;200;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(MulDivTest "C:/Projects/Quick/MinSizeRel/test_mul_div.exe")
  set_tests_properties(MulDivTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;200;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MulDivTest "C:/Projects/Quick/RelWithDebInfo/test_mul_div.exe")
  set_tests_properties(MulDivTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;200;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(MulDivTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BitwiseTest "C:/Projects/Quick/Debug/test_bitwise.exe")
  set_tests_properties(BitwiseTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;205;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BitwiseTest "C:/Projects/Quick/Release/test_bitwise.exe")
  set_tests_properties(BitwiseTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;205;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BitwiseTest "C:/Projects/Quick/MinSizeRel/test_bitwise.exe")
  set_tests_properties(BitwiseTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;205;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BitwiseTest "C:/Projects/Quick/RelWithDebInfo/test_bitwise.exe")
  set_tests_properties(BitwiseTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;205;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(BitwiseTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NegTest "C:/Projects/Quick/Debug/test_neg.exe")
  set_tests_properties(NegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;210;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NegTest "C:/Projects/Quick/Release/test_neg.exe")
  set_tests_properties(NegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;210;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NegTest "C:/Projects/Quick/MinSizeRel/test_neg.exe")
  set_tests_properties(NegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;210;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NegTest "C:/Projects/Quick/RelWithDebInfo/test_neg.exe")
  set_tests_properties(NegTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;210;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(NegTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ComparisonParserTest "C:/Projects/Quick/Debug/test_comparison.exe")
  set_tests_properties(ComparisonParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;216;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ComparisonParserTest "C:/Projects/Quick/Release/test_comparison.exe")
  set_tests_properties(ComparisonParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;216;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ComparisonParserTest "C:/Projects/Quick/MinSizeRel/test_comparison.exe")
  set_tests_properties(ComparisonParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;216;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ComparisonParserTest "C:/Projects/Quick/RelWithDebInfo/test_comparison.exe")
  set_tests_properties(ComparisonParserTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;216;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ComparisonParserTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedSCCPTest "C:/Projects/Quick/Debug/test_enhanced_sccp.exe")
  set_tests_properties(EnhancedSCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;222;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedSCCPTest "C:/Projects/Quick/Release/test_enhanced_sccp.exe")
  set_tests_properties(EnhancedSCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;222;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedSCCPTest "C:/Projects/Quick/MinSizeRel/test_enhanced_sccp.exe")
  set_tests_properties(EnhancedSCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;222;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedSCCPTest "C:/Projects/Quick/RelWithDebInfo/test_enhanced_sccp.exe")
  set_tests_properties(EnhancedSCCPTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;222;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(EnhancedSCCPTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedDCETest "C:/Projects/Quick/Debug/test_enhanced_dce.exe")
  set_tests_properties(EnhancedDCETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;227;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedDCETest "C:/Projects/Quick/Release/test_enhanced_dce.exe")
  set_tests_properties(EnhancedDCETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;227;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedDCETest "C:/Projects/Quick/MinSizeRel/test_enhanced_dce.exe")
  set_tests_properties(EnhancedDCETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;227;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedDCETest "C:/Projects/Quick/RelWithDebInfo/test_enhanced_dce.exe")
  set_tests_properties(EnhancedDCETest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;227;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(EnhancedDCETest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LICMTest "C:/Projects/Quick/Debug/test_licm.exe")
  set_tests_properties(LICMTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;232;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LICMTest "C:/Projects/Quick/Release/test_licm.exe")
  set_tests_properties(LICMTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;232;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LICMTest "C:/Projects/Quick/MinSizeRel/test_licm.exe")
  set_tests_properties(LICMTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;232;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LICMTest "C:/Projects/Quick/RelWithDebInfo/test_licm.exe")
  set_tests_properties(LICMTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;232;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(LICMTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(IntegrationTest "C:/Projects/Quick/Debug/test_integration.exe")
  set_tests_properties(IntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;237;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(IntegrationTest "C:/Projects/Quick/Release/test_integration.exe")
  set_tests_properties(IntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;237;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(IntegrationTest "C:/Projects/Quick/MinSizeRel/test_integration.exe")
  set_tests_properties(IntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;237;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(IntegrationTest "C:/Projects/Quick/RelWithDebInfo/test_integration.exe")
  set_tests_properties(IntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;237;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(IntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ASMValidationTest "C:/Projects/Quick/Debug/test_asm_validation.exe")
  set_tests_properties(ASMValidationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;243;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ASMValidationTest "C:/Projects/Quick/Release/test_asm_validation.exe")
  set_tests_properties(ASMValidationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;243;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ASMValidationTest "C:/Projects/Quick/MinSizeRel/test_asm_validation.exe")
  set_tests_properties(ASMValidationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;243;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ASMValidationTest "C:/Projects/Quick/RelWithDebInfo/test_asm_validation.exe")
  set_tests_properties(ASMValidationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;243;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ASMValidationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ObjectGenerationTest "C:/Projects/Quick/Debug/test_object_generation.exe")
  set_tests_properties(ObjectGenerationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;248;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ObjectGenerationTest "C:/Projects/Quick/Release/test_object_generation.exe")
  set_tests_properties(ObjectGenerationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;248;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ObjectGenerationTest "C:/Projects/Quick/MinSizeRel/test_object_generation.exe")
  set_tests_properties(ObjectGenerationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;248;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ObjectGenerationTest "C:/Projects/Quick/RelWithDebInfo/test_object_generation.exe")
  set_tests_properties(ObjectGenerationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;248;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ObjectGenerationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedCodeGenTest "C:/Projects/Quick/Debug/test_enhanced_codegen.exe")
  set_tests_properties(EnhancedCodeGenTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;253;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedCodeGenTest "C:/Projects/Quick/Release/test_enhanced_codegen.exe")
  set_tests_properties(EnhancedCodeGenTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;253;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedCodeGenTest "C:/Projects/Quick/MinSizeRel/test_enhanced_codegen.exe")
  set_tests_properties(EnhancedCodeGenTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;253;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedCodeGenTest "C:/Projects/Quick/RelWithDebInfo/test_enhanced_codegen.exe")
  set_tests_properties(EnhancedCodeGenTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;253;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(EnhancedCodeGenTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedTargetsTest "C:/Projects/Quick/Debug/test_enhanced_targets.exe")
  set_tests_properties(EnhancedTargetsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;259;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedTargetsTest "C:/Projects/Quick/Release/test_enhanced_targets.exe")
  set_tests_properties(EnhancedTargetsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;259;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedTargetsTest "C:/Projects/Quick/MinSizeRel/test_enhanced_targets.exe")
  set_tests_properties(EnhancedTargetsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;259;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedTargetsTest "C:/Projects/Quick/RelWithDebInfo/test_enhanced_targets.exe")
  set_tests_properties(EnhancedTargetsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;259;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(EnhancedTargetsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MemoryOperationsTest "C:/Projects/Quick/Debug/test_memory_operations.exe")
  set_tests_properties(MemoryOperationsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;264;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MemoryOperationsTest "C:/Projects/Quick/Release/test_memory_operations.exe")
  set_tests_properties(MemoryOperationsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;264;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(MemoryOperationsTest "C:/Projects/Quick/MinSizeRel/test_memory_operations.exe")
  set_tests_properties(MemoryOperationsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;264;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MemoryOperationsTest "C:/Projects/Quick/RelWithDebInfo/test_memory_operations.exe")
  set_tests_properties(MemoryOperationsTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;264;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(MemoryOperationsTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ComparisonControlFlowTest "C:/Projects/Quick/Debug/test_comparison_control_flow.exe")
  set_tests_properties(ComparisonControlFlowTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;269;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ComparisonControlFlowTest "C:/Projects/Quick/Release/test_comparison_control_flow.exe")
  set_tests_properties(ComparisonControlFlowTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;269;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ComparisonControlFlowTest "C:/Projects/Quick/MinSizeRel/test_comparison_control_flow.exe")
  set_tests_properties(ComparisonControlFlowTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;269;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ComparisonControlFlowTest "C:/Projects/Quick/RelWithDebInfo/test_comparison_control_flow.exe")
  set_tests_properties(ComparisonControlFlowTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;269;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ComparisonControlFlowTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ProfilingTest "C:/Projects/Quick/Debug/test_profiling.exe")
  set_tests_properties(ProfilingTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;275;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ProfilingTest "C:/Projects/Quick/Release/test_profiling.exe")
  set_tests_properties(ProfilingTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;275;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ProfilingTest "C:/Projects/Quick/MinSizeRel/test_profiling.exe")
  set_tests_properties(ProfilingTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;275;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ProfilingTest "C:/Projects/Quick/RelWithDebInfo/test_profiling.exe")
  set_tests_properties(ProfilingTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;275;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(ProfilingTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SIMDTest "C:/Projects/Quick/Debug/test_simd.exe")
  set_tests_properties(SIMDTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;281;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SIMDTest "C:/Projects/Quick/Release/test_simd.exe")
  set_tests_properties(SIMDTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;281;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SIMDTest "C:/Projects/Quick/MinSizeRel/test_simd.exe")
  set_tests_properties(SIMDTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;281;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SIMDTest "C:/Projects/Quick/RelWithDebInfo/test_simd.exe")
  set_tests_properties(SIMDTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;281;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(SIMDTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FusionTest "C:/Projects/Quick/Debug/test_fusion.exe")
  set_tests_properties(FusionTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;287;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FusionTest "C:/Projects/Quick/Release/test_fusion.exe")
  set_tests_properties(FusionTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;287;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FusionTest "C:/Projects/Quick/MinSizeRel/test_fusion.exe")
  set_tests_properties(FusionTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;287;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FusionTest "C:/Projects/Quick/RelWithDebInfo/test_fusion.exe")
  set_tests_properties(FusionTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;287;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(FusionTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DebugInfoTest "C:/Projects/Quick/Debug/test_debuginfo.exe")
  set_tests_properties(DebugInfoTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;293;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DebugInfoTest "C:/Projects/Quick/Release/test_debuginfo.exe")
  set_tests_properties(DebugInfoTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;293;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DebugInfoTest "C:/Projects/Quick/MinSizeRel/test_debuginfo.exe")
  set_tests_properties(DebugInfoTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;293;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DebugInfoTest "C:/Projects/Quick/RelWithDebInfo/test_debuginfo.exe")
  set_tests_properties(DebugInfoTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;293;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(DebugInfoTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedIntegrationTest "C:/Projects/Quick/Debug/test_integration_enhanced.exe")
  set_tests_properties(EnhancedIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;299;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedIntegrationTest "C:/Projects/Quick/Release/test_integration_enhanced.exe")
  set_tests_properties(EnhancedIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;299;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedIntegrationTest "C:/Projects/Quick/MinSizeRel/test_integration_enhanced.exe")
  set_tests_properties(EnhancedIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;299;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedIntegrationTest "C:/Projects/Quick/RelWithDebInfo/test_integration_enhanced.exe")
  set_tests_properties(EnhancedIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;299;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(EnhancedIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BenchmarkTest "C:/Projects/Quick/Debug/test_benchmark.exe")
  set_tests_properties(BenchmarkTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;305;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BenchmarkTest "C:/Projects/Quick/Release/test_benchmark.exe")
  set_tests_properties(BenchmarkTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;305;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BenchmarkTest "C:/Projects/Quick/MinSizeRel/test_benchmark.exe")
  set_tests_properties(BenchmarkTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;305;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BenchmarkTest "C:/Projects/Quick/RelWithDebInfo/test_benchmark.exe")
  set_tests_properties(BenchmarkTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;305;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(BenchmarkTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WindowsRiscVEnhancedTest "C:/Projects/Quick/Debug/test_windows_riscv_enhanced.exe")
  set_tests_properties(WindowsRiscVEnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;311;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WindowsRiscVEnhancedTest "C:/Projects/Quick/Release/test_windows_riscv_enhanced.exe")
  set_tests_properties(WindowsRiscVEnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;311;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WindowsRiscVEnhancedTest "C:/Projects/Quick/MinSizeRel/test_windows_riscv_enhanced.exe")
  set_tests_properties(WindowsRiscVEnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;311;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WindowsRiscVEnhancedTest "C:/Projects/Quick/RelWithDebInfo/test_windows_riscv_enhanced.exe")
  set_tests_properties(WindowsRiscVEnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;311;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(WindowsRiscVEnhancedTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RiscV64EnhancedTest "C:/Projects/Quick/Debug/test_riscv64_enhanced.exe")
  set_tests_properties(RiscV64EnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;317;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RiscV64EnhancedTest "C:/Projects/Quick/Release/test_riscv64_enhanced.exe")
  set_tests_properties(RiscV64EnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;317;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RiscV64EnhancedTest "C:/Projects/Quick/MinSizeRel/test_riscv64_enhanced.exe")
  set_tests_properties(RiscV64EnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;317;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RiscV64EnhancedTest "C:/Projects/Quick/RelWithDebInfo/test_riscv64_enhanced.exe")
  set_tests_properties(RiscV64EnhancedTest PROPERTIES  WORKING_DIRECTORY "C:/Projects/Quick" _BACKTRACE_TRIPLES "C:/Projects/Quick/CMakeLists.txt;317;add_test;C:/Projects/Quick/CMakeLists.txt;0;")
else()
  add_test(RiscV64EnhancedTest NOT_AVAILABLE)
endif()
